FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY serva/requirements.txt .

RUN pip install -r requirements.txt

COPY serva/app.py .

EXPOSE 5001

CMD ["python", "app.py"]