FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY servb/requirements.txt .

RUN pip install -r requirements.txt

COPY servb/app.py .

EXPOSE 5002

CMD ["python", "app.py"]