FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY users/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY users/app.py .

EXPOSE 5001

CMD ["python", "app.py"]
