FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY pedidos/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY pedidos/app.py .

EXPOSE 5002

CMD ["python", "app.py"]
